image: node:latest

stages:
    - test_backend
    - test_frontend

services:
    - mongo

test_backend:
    stage: test_backend
    script:
        - cd backend
        - npm ci
        - npm test
    cache:
        paths:
            - backend/node_modules/

test_frontend:
    stage: test_frontend
    image: trion/ng-cli-karma
    script:
        - cd frontend/garbage-hunter-frontend
        - npm ci
        - npm run test-ci
    cache:
        paths:
            - frontend/garbage-hunter-frontend/node_modules/
