version: "3.7"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    links:
      - mongo
    build:
      context: ./
      dockerfile: docker/docker-backend/Dockerfile
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./
      dockerfile: docker/docker-frontend/Dockerfile
    ports:
      - "80:80"
